apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: skgupta77159githubio-react-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31110